export const sliders = [
    { title: "Welcome to the magical Garage", imgSrc: "https://drive.google.com/uc?export=view&id=161M10s0C0hyLC-vlwIq0YxMEEYQl2sDR"},
    { title: "World Premiere Marcedez-Benz GLc", imgSrc: "https://drive.google.com/uc?export=view&id=1mdSmI-9xqGxWnNy63gY28wvRPRaVZ_cK" },
    { title: "Sunglass for exclusive visibility", imgSrc: "https://drive.google.com/uc?export=view&id=1Q8JTpdEYNq85RPyB3kTxtNKFpS9HI8am" },
    { title: "World Premiere EQS-Suv", imgSrc: "https://drive.google.com/uc?export=view&id=1NgegkyLmYPvlwUmWErpFIgy7H4vx-TL9" },
    { title: "Project MAYBACH", imgSrc: "https://drive.google.com/uc?export=view&id=15nhjx587xH1B1nhdCUfk-vpiWmOExHbv" },
    { title: "The new G-CLASS Private Lounge", imgSrc: "https://drive.google.com/uc?export=view&id=10gFx4-CZiDlYSyoYI7sbzMDls1gRRqnP" },
    { title: "Welcome to the magical Garage", imgSrc: "https://drive.google.com/uc?export=view&id=1YzHkBqYX4068IxqJ7jErL1-cfWTbpeu4" },
    { title: "World Premiere Marcedez-Benz GLc", imgSrc: "https://drive.google.com/uc?export=view&id=13Dwl4G9nN4DcxTHtBinB2JzljPwXw0xK" },
    { title: "Sunglass for exclusive visibility", imgSrc: "https://drive.google.com/uc?export=view&id=12qwp1on8wx8zYDt28RI5av6JePzsm3iz" },
    { title: "World Premiere EQS-Suv", imgSrc: "https://drive.google.com/uc?export=view&id=1zm2qLxK1Hu6B9QwqYg_LMuxqx26665sg" },
    { title: "Project MAYBACH", imgSrc: "https://drive.google.com/uc?export=view&id=1G6UOfDfUCH_HPVIm5sbxEV0CUDrHkz2Y" },
    { title: "The new G-CLASS Private Lounge", imgSrc: "https://drive.google.com/uc?export=view&id=1Q8JTpdEYNq85RPyB3kTxtNKFpS9HI8am" },
    { title: "Welcome to the magical Garage", imgSrc: "https://drive.google.com/uc?export=view&id=161M10s0C0hyLC-vlwIq0YxMEEYQl2sDR" },
    { title: "World Premiere Marcedez-Benz GLc", imgSrc: "https://drive.google.com/uc?export=view&id=13Dwl4G9nN4DcxTHtBinB2JzljPwXw0xK" },
    { title: "Sunglass for exclusive visibility", imgSrc: "https://drive.google.com/uc?export=view&id=1mdSmI-9xqGxWnNy63gY28wvRPRaVZ_cK" },
    { title: "World Premiere EQS-Suv", imgSrc: "https://drive.google.com/uc?export=view&id=12qwp1on8wx8zYDt28RI5av6JePzsm3iz" },
    { title: "Project MAYBACH", imgSrc: "https://drive.google.com/uc?export=view&id=13Dwl4G9nN4DcxTHtBinB2JzljPwXw0xK" },
    { title: "The new G-CLASS Private Lounge", imgSrc: "https://drive.google.com/uc?export=view&id=15nhjx587xH1B1nhdCUfk-vpiWmOExHbv" }
]